name: build-and-deploy
on:
  push:
    branches:
      - main
jobs:
  setup-build-push-deploy:
    name: Setup, Build, Push and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: github-actions-service-account@pma-learn.iam.gserviceaccount.com
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build & Publish
      run: |
        docker build -t gcr.io/pma-learn/katana-sample-app .
        docker push gcr.io/pma-learn/katana-sample-app        
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy Cloud Run
      run: |
        gcloud run deploy katana-sample-app --image gcr.io/pma-learn/katana-sample-app \
        --platform managed \
        --allow-unauthenticated \
        --memory 512M